-- Add new columns for visitor workflow and parking integration
ALTER TABLE public.visitors
ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS resident_id text REFERENCES public.residents(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS block_id text REFERENCES public.blocks(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS visitor_count integer NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS otp text,
ADD COLUMN IF NOT EXISTS otp_expires_at timestamptz,
ADD COLUMN IF NOT EXISTS parking_slot_id text REFERENCES public.parking_slots(id) ON DELETE SET NULL;

-- Remove the NOT NULL constraint from check_in as visitors start as pending
ALTER TABLE public.visitors ALTER COLUMN check_in DROP NOT NULL;
ALTER TABLE public.visitors ALTER COLUMN check_in DROP DEFAULT;

-- Update RLS for visitors so residents can view their own visitors
DROP POLICY IF EXISTS "visitors_select" ON public.visitors;
CREATE POLICY "visitors_select"
  ON public.visitors FOR SELECT
  USING (
    public.profile_role() = 'admin'
    OR public.profile_role() = 'security'
    OR exists (
      select 1 from public.residents r
      where r.id = visitors.resident_id and r.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "visitors_update" ON public.visitors;
CREATE POLICY "visitors_update"
  ON public.visitors FOR UPDATE
  USING (
    public.profile_role() = 'admin'
    OR public.profile_role() = 'security'
    OR exists (
      select 1 from public.residents r
      where r.id = visitors.resident_id and r.user_id = auth.uid()
    )
  );

-- Create Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  message text,
  type text not null, -- 'visitor_request', 'visitor_approved', 'visitor_rejected', etc.
  reference_id text, -- e.g. visitor id
  read boolean not null default false,
  created_at timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS notifications_user_id_idx ON public.notifications (user_id);
CREATE INDEX IF NOT EXISTS notifications_read_idx ON public.notifications (read);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notifications_select" ON public.notifications;
CREATE POLICY "notifications_select"
  ON public.notifications FOR SELECT
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "notifications_update" ON public.notifications;
CREATE POLICY "notifications_update"
  ON public.notifications FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Allow security/admin to insert notifications (or RPC functions)
-- Since notifications are often generated by triggers or RPCs, we can just allow authenticated inserts for now,
-- but we only want users to select their own.
DROP POLICY IF EXISTS "notifications_insert" ON public.notifications;
CREATE POLICY "notifications_insert"
  ON public.notifications FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Update parking_slots RLS to ensure security can update them
DROP POLICY IF EXISTS "parking_write_admin" ON public.parking_slots;
CREATE POLICY "parking_write_admin"
  ON public.parking_slots FOR ALL
  USING (public.profile_role() IN ('admin', 'security'))
  WITH CHECK (public.profile_role() IN ('admin', 'security'));
